[[sections]]
name = "html"
description = "HTML is the standard markup language for Web pages."
features = [
  "Create your own Website",
  "Describes the structure of a Web page",
  "Consists of a series of elements",
  "Elements label content like headings, paragraphs, links, etc."
]

[[sections]]
name = "css"
description = "CSS is the language used to style a Web page."
features = [
  "Describes how HTML elements should be displayed",
  "Stands for Cascading Style Sheets",
  "Saves work by controlling layout across multiple web pages",
  "External stylesheets are stored in CSS files",
  "Defines styles for web pages, including design, layout, and responsiveness"
]

[[sections]]
name = "javascript"
description = "JavaScript is the programming language of the Web."
features = [
  "Part of the trio of languages web developers must learn",
  "Can change HTML content using methods like getElementById()",
  "Can change HTML attribute values",
  "Can change HTML styles (CSS)",
  "Can hide and show HTML elements"
]
