[intro]
content = """
HTML is the standard markup language for Web pages.

With HTML, you can create your own Website.
HTML stands for Hyper Text Markup Language
HTML is the standard markup language for creating Web pages
HTML describes the structure of a Web page
HTML consists of a series of elements
HTML elements tell the browser how to display the content
HTML elements label pieces of content such as "this is a heading", "this is a paragraph", "this is a link", etc.

CSS is the language we use to style a Web page.
CSS is the language we use to style an HTML document.

CSS describes how HTML elements should be displayed
CSS stands for Cascading Style Sheets
CSS describes how HTML elements are to be displayed on screen, paper, or in other media
CSS saves a lot of work. It can control the layout of multiple web pages all at once
External stylesheets are stored in CSS files
CSS is used to define styles for your web pages, including the design,
layout and variations in display for different devices and screen sizes.
CSS removed the style formatting from the HTML page!

JavaScript is the programming language of the Web.
JavaScript is one of the 3 languages all web developers must learn:

   1. HTML to define the content of web pages

   2. CSS to specify the layout of web pages

   3. JavaScript to program the behavior of web pages

   JavaScript Can Change HTML Content
One of many JavaScript HTML methods is getElementById().

JavaScript Can Change HTML Attribute Values
In this example, JavaScript changes the value of the src (source) attribute of an <img> tag:
JavaScript Can Change HTML Styles (CSS)
Changing the style of an HTML element is a variant of changing an HTML attribute:
JavaScript Can Hide HTML Elements
Hiding HTML elements can be done by changing the display style:

JavaScript Can Show HTML Elements
Showing hidden HTML elements can also be done by changing the display style:
"""
