[article1]
date = "12/11/2023"
references = [
  "https://www.simform.com/blog/how-do-online-auctions-work/",
  "https://dev.to/hirendhaduk_/tech-stack-for-online-auctions-platform-what-you-need-to-know-4c3c",
  "https://relevant.software/blog/how-to-build-bidding-website/"
]
