https://dev.to/favourmark05/writing-clean-code-best-practices-and-principles-3amh?ref=dailydev

https://dev.to/vedangit/a-minimalists-guide-to-software-development-less-code-more-elegance-37n1?ref=dailydev
